---
# handlers file for ansible-role-deploy_sysstat

- name: Restart systat service
  ansible.builtin.service:
    name: '{{ dsys_service_name }}'
    state: restarted
    enabled: true
  when: dsys_service_enable | bool
